### ISSUE TITLE
不知道作者考虑增加一套登录成功以后，查看本地文件的命令吗？

### ISSUE THREAD

**Issue by lepig** [wangbjun/go-micloud#1]
登录成功以后执行`ls`查看的是云盘上的文件列表。我想的是，有没有考虑过增加一套命令，比如`lls`查看的就是主机当前目录的文件列表，`lcd`切换本机目录，等等。
这样的好处是我在一个窗口就可以操作我想上传或下载的文件。现在是得打开2个窗口，而且下载的文件是我当前登录的位置。

**Comment by wangbjun** [comment]
考虑过，但是感觉容易混淆，下载的文件位置默认是当前终端打开的时候目录，其实我更倾向于加一个参数（比如 -d）指定下载文件的存放位置，这个我后期会完善一下。
