### ISSUE TITLE
Mac用户求一个编译好的命令，或者，如何编译GO，没用过

### ISSUE THREAD

**Issue by royaso** [wangbjun/go-micloud#2]

**Comment by wangbjun** [comment]
好的，安排上了，你看看release里面，我编译了一个，但是我没有mac设备，不确定可以用

https://github.com/wangbjun/go-micloud/releases/download/1.2/micloud_x86_mac

**Comment by royaso** [comment]
感谢！这么快就解决了。能用！！

ps:
micloud - MiCloud Third Party Console Client Written By Golang

是用go语言写的介词是IN，作者是用BY
